name: 'Test Report'
on:
  workflow_run:
    workflows: ['build-test']
    types:
      - completed
jobs:
  petstore-report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: petstore-test-results
        name: Xunit Tests
        path: '*.trx'
        reporter: dotnet-trx
        
  uitestingplayground-report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: uitestingplayground-test-results
        name: Xunit Tests
        path: '*.trx'
        reporter: dotnet-trx